# Generated by Django 4.2.6 on 2023-10-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExampleBlankJsonFieldModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("my_json", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExampleJsonFieldModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("my_json", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="ExampleUneditableJsonFieldModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("my_json", models.JSONField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
