name: publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.2

      - name: Build a binary wheel and a source tarball
        run: poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          verbose: true
